//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WriteFlash.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WRITEFLASH_DIALOG           102
#define IDS_TIMEOUT                     103
#define IDS_CONNECT                     104
#define IDS_SUCCESS                     105
#define IDS_FAIL                        106
#define IDS_PORT_FAIL                   107
#define IDS_WAIT                        108
#define IDS_INIT                        109
#define IDS_WAIT_NEWMET                 110
#define IDR_MAINFRAME                   111
#define IDS_VERIFPHONESTATE_FAIL        111
#define IDD_DIALOG_SETIMEI              112
#define IDS_CABLEINDICATOR_CONN         112
#define IDS_CREATPHASE_ERR              113
#define IDS_CABLEINDICATOR_DISCONN      114
#define IDS_STOP                        115
#define IDS_IMEI_LENTH                  116
#define IDS_BT_LENTH                    117
#define IDS_IMEI_ERR                    118
#define IDS_READ_FAIL                   119
#define IDS_READ_PASS                   120
#define IDS_CHECK                       121
#define IDS_WRITETIME                   122
#define IDS_SPPH_SUCC                   123
#define IDS_SPPH_FAIL                   124
#define IDS_SPPH_OPEN_PORT              125
#define IDS_SPPH_STATION_NOT_EXIST      126
#define IDS_SPPH_STATION_NOT_PASSED     127
#define IDS_SPPH_WRITE_PRODUCTINFO_FAIL 128
#define IDS_SPPH_READ_PRODUCTINFO_FAIL  129
#define IDS_SPPH_READ_MAGIC_NUMBER_FAIL 130
#define IDS_SPPH_DEFAULT                131
#define IDS_SPPH_INVALID_SPPH_OBJECT    132
#define IDD_DIALOG_MODESEL              132
#define IDS_REUSE_IMEI                  133
#define IDS_OPEN_SAVEFILE_ERR           134
#define IDS_STATIC_PASS                 135
#define IDS_STATIC_FAIL                 136
#define IDS_STATIC_YIELD                137
#define IDS_INVALID_PRODUCTINFO         138
#define IDS_SPPH_NOT_TESTED             139
#define IDS_SPPH_BUFFER_SMALL           140
#define IDS_SPPH_INVALID_MAGIC          141
#define IDS_VERSION_READ                142
#define IDS_VERSION_ERR                 143
#define IDS_IMEI_REJECT                 144
#define IDS_WARNING                     145
#define IDS_WIFI_FORMAT                 146
#define IDS_WIFI_SIX                    147
#define IDS_MODEDISP_NEWMODE            148
#define IDS_MODEDISP_OLDMODE            149
#define IDS_MODEDISP_NEWMODE_TIPS       150
#define IDS_SN_LENTH                    151
#define IDS_MODEDISP_OLDMODE_TIPS       152
#define IDS_ERRORSTR_UNKNOWN            153
#define IDS_TIPSSTR_DISAUTOUSB          154
#define IDS_STRING_STATIC_CONN          155
#define IDS_STRING_STATIC_DISCONN       156
#define IDS_WRITESN_FAIL                157
#define IDS_SN_ERR                      158
#define IDS_AUTOCLOSEUSB                159
#define IDS_GENCODETYPE_ITEM1           160
#define IDS_GENCODETYPE_ITEM2           161
#define IDS_GENCODETYPE_ITEM3           162
#define IDS_SET_VERSIONLENGTH_ERR       163
#define IDS_IMEI_REPEAT                 164
#define IDS_CHKBT_FAIL                  165
#define IDS_CHKWIFI_FAIL                166
#define IDS_CHKIMEI_FAIL                167
#define IDS_CHK_PASS                    168
#define IDS_CHK_FAIL                    169
#define IDS_INVALID_INPUT_BTADDR        170
#define IDS_INVALID_INPUT_WFADDR        171
#define IDS_AP_VER_ERR                  172
#define IDS_OPEN_CDROM_FAIL             173
#define IDS_READ_CUREF_FAIL             174
#define IDS_WRITE_CUREF_FAIL            175
#define IDS_SEND_AT_CMD_ERR             176
#define IDC_BUTTON_SET                  1003
#define IDC_BUTTON_START                1004
#define IDC_COMBO_PORT                  1005
#define IDC_CHECK_IMEI1                 1006
#define IDC_CHECK_PHASE                 1008
#define IDC_CHECK_IMEI2                 1010
#define IDC_STATIC_IMIE4                1011
#define IDC_EDIT_AUTOIMEI               1012
#define IDC_CHECK_AUTOIMEI              1013
#define IDC_EDIT_IMEISENIOR             1014
#define IDC_EDIT_BT                     1015
#define IDC_EDIT_IMEITHIRD              1016
#define IDC_STATIC_IMIE1                1017
#define IDC_STATIC_IMIE2                1018
#define IDC_STATIC_IMIE3                1019
#define IDC_STATIC_BT                   1020
#define IDC_CHECK_SAMEIMEI              1021
#define IDC_EDIT_SNSENIOR               1021
#define IDC_EDIT_IMEIMAIN               1022
#define IDC_BUTTON_READ                 1023
#define IDC_STATIC_WIFI                 1024
#define IDC_EDIT_IMEIFOUR               1025
#define IDC_STATIC_MESSAGE              1026
#define IDC_CHECK_BT                    1027
#define IDC_EDIT_SNMAIN                 1027
#define IDC_CHECK_AUTOBT                1028
#define IDC_STATIC_SN1                  1028
#define IDC_CHECK_AUTOWIFI              1029
#define IDC_STATIC_SN2                  1029
#define IDC_BUTTON_STOP                 1030
#define IDC_STATIC_VERSION              1031
#define IDC_STATIC_BUILD                1032
#define IDC_STATIC_PASS                 1033
#define IDC_STATIC_FAIL                 1034
#define IDC_STATIC_PASSYIELD            1035
#define IDC_EDIT_WIFI                   1036
#define IDC_CHECK_TXT                   1037
#define IDC_CHECK_MDB                   1038
#define IDC_CHECK_SAVE                  1039
#define IDC_CHECK_REPEAT                1040
#define IDC_CHECK_VALID                 1041
#define IDC_CHECK_IMEI3                 1042
#define IDC_CHECK_IMEI4                 1043
#define IDC_CHECK_WIFI                  1044
#define IDC_CHECK_VER                   1045
#define IDC_EDIT_VER                    1046
#define IDC_STATIC_WARNING              1047
#define IDC_CHECK_AP_VER                1047
#define IDC_COMBO_CONNMODE              1048
#define IDC_EDIT_AP_VER                 1048
#define IDC_STATIC_PORT                 1049
#define IDC_STATIC_PORT_O               1050
#define IDC_STATIC_CONNMODE             1052
#define IDC_EDIT_PORTNUM                1053
#define IDC_STATIC_PORTINDICATOR        1054
#define IDC_COMBO_FORPORT               1056
#define IDC_BUTTON2                     1057
#define IDC_STATIC_MODEDISP             1058
#define IDC_RADIO_MODE1                 1059
#define IDC_RADIO_MODE2                 1060
#define IDC_STATIC_MODEDESRP_NORMAL     1061
#define IDC_STATIC_MODEDESRP_WROKING    1062
#define IDC_CHECK_DIS_AUTOUSB           1066
#define IDC_CHECK_SN1                   1067
#define IDC_CHECK_SN2                   1068
#define IDC_EDIT_INITADDR               1069
#define IDC_EDIT_INITADDR_BT            1069
#define IDC_CHECK_AUTOSN1               1070
#define IDC_CHECK_AUTOSN2               1071
#define IDC_EDIT_INITADDR_WIFI          1072
#define IDC_STATIC_MAINFRAME            1073
#define IDC_EDIT_BTADDRPATH             1073
#define IDC_STATIC_SNFRAME              1074
#define IDC_STATIC_VERSIONFRAME         1075
#define IDC_RADIO_GENADDR_TYPE1         1076
#define IDC_RADIO_GENADDR_BT_TYPE1      1076
#define IDC_RADIO_GENADDR_TYPE2         1077
#define IDC_RADIO_GENADDR_BT_TYPE2      1077
#define IDC_STATIC_GENADDRTYPE          1078
#define IDC_STATIC_GENADDRTYPE_BT       1078
#define IDC_STATIC_AUTOUSBTIPS          1079
#define IDC_STATIC_GENADDRTYPE_WIFI     1079
#define IDC_COMBO_GENIMEI1TYPE          1080
#define IDC_COMBO_GENIMEI2TYPE          1081
#define IDC_COMBO_GENIMEI3TYPE          1082
#define IDC_COMBO_GENIMEI4TYPE          1083
#define IDC_RADIO_GENADDR_WIFI_TYPE1    1084
#define IDC_RADIO_GENADDR_WIFI_TYPE2    1085
#define IDC_CHECK_IMEI_ONREAD           1086
#define IDC_BTN_ASSBTADDR               1087
#define IDC_EDIT_WIFIADDRPATH           1088
#define IDC_CHECK_NOT_REBOOT_DUT        1088
#define IDC_BTN_ASSWIFIADDR             1089
#define IDC_STATIC_BTADAS               1090
#define IDC_STATIC_WIFIADAS             1091
#define IDC_STATIC_AP_VER               1092
#define IDC_EDIT_CUREF1                 1093
#define IDC_EDIT_CUREF2                 1094
#define IDC_EDIT_CUREF3                 1095
#define IDC_EDIT_CUREF4                 1096
#define IDC_EDIT_CUREF5                 1097
#define IDC_EDIT_CUREF6                 1098
#define IDC_EDIT_CUREF7                 1099
#define IDC_EDIT_CUREF8                 1100
#define IDC_EDIT_CUREF9                 1101
#define IDC_EDIT_CUREF10                1102
#define IDC_EDIT_CUREF11                1103
#define IDC_EDIT_CUREF12                1104
#define IDC_EDIT_CUREF13                1105
#define IDC_EDIT_CUREF14                1106
#define IDC_EDIT_CUREF15                1107
#define IDC_EDIT_CUREF16                1108
#define IDC_EDIT_CUREF17                1109
#define IDC_EDIT_CUREF18                1110
#define IDC_EDIT_CUREF19                1111
#define IDC_EDIT_CUREF20                1112
#define IDC_EDIT_CUREF21                1113
#define IDC_EDIT_CUREF22                1114
#define IDC_EDIT_CUREF23                1115
#define IDC_EDIT_CUREF24                1116
#define IDC_EDIT_SW_VERSION             1117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
